[project]
name = "pylearn"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pymysql>=1.1.1",
    "redis>=5.2.1",
    "requests>=2.32.3",
]
